// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SureBackup.Infrastructure.Database;

#nullable disable

namespace SureBackup.Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SureBackup.Domain.Entities.BackupSetting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("BackupKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackupOperationPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedBackupKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("EncryptedBackupKey");

                    b.Property<bool>("EncryptionBackup")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EncryptionBackup");

                    b.Property<string>("FTPEncryptedPassword")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("FTPEncryptedPassword");

                    b.Property<string>("FTPEncryptedUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("FTPEncryptedUrl");

                    b.Property<string>("FTPEncryptedUsername")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("FTPEncryptedUsername");

                    b.Property<string>("FTPPassword")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FTPUpload")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FTPUpload");

                    b.Property<string>("FTPUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FTPUsername")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HostSizeInBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HostSizeInBytes");

                    b.Property<int>("IntervalMiliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IntervalMiliseconds");

                    b.HasKey("ID");

                    b.ToTable("BackupSetting", (string)null);
                });

            modelBuilder.Entity("SureBackup.Domain.Entities.DatabaseInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Database")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("EncryptedConnectionString");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("ID");

                    b.ToTable("DatabaseInfo", (string)null);
                });

            modelBuilder.Entity("SureBackup.Domain.Entities.Log", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("DatabaseInfoID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DatabaseInfoID");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("Date");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Message");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Type");

                    b.HasKey("ID");

                    b.HasIndex("DatabaseInfoID");

                    b.ToTable("Log", (string)null);
                });

            modelBuilder.Entity("SureBackup.Domain.Entities.Log", b =>
                {
                    b.HasOne("SureBackup.Domain.Entities.DatabaseInfo", "DatabaseInfo")
                        .WithMany("BackupLogs")
                        .HasForeignKey("DatabaseInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatabaseInfo");
                });

            modelBuilder.Entity("SureBackup.Domain.Entities.DatabaseInfo", b =>
                {
                    b.Navigation("BackupLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
